apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: /whoami
    repoURL: https://github.com/Yggdrasil/podinfo-deploy
    targetRevision: master
  syncPolicy:
    automated:
      prune: true